name: Terraform Deploy to GCP

on:
  push:
    branches: [main]

jobs:
  terraform:
    name: Terraform Plan and Apply
    runs-on: ubuntu-latest
    environment: dev

    env:
      ACTIONS_STEP_DEBUG: true  # Enables verbose debug output

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          token_format: 'access_token'
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.SERVICE_ACCOUNT_EMAIL }}
          access_token_scopes: https://www.googleapis.com/auth/cloud-platform
          audience: sts.googleapis.com  # <- Add this line to force the correct audience

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init
        working-directory: environment/dev

      - name: Terraform Plan
        run: terraform plan -out=tfplan
        working-directory: environment/dev

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan
        working-directory: environment/dev
