name: Terraform Deploy to GCP

on:
  push:
    branches: [main]

jobs:
  terraform:
    name: Terraform Plan and Apply
    runs-on: ubuntu-latest
    environment: dev

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: "projects/915398988184/locations/global/workloadIdentityPools/github-actions-pool/providers/github-actions-pool"
          service_account: gha-deployer@stocks-415200.iam.gserviceaccount.com
          access_token_scopes: "https://www.googleapis.com/auth/cloud-platform"
          export_environment_variables: true

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -out=tfplan

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan
